---
- name: "Install kind cluster '{{ kind_cluster_name }}' (Wait until success)"
  block:


    # - name: "Debug"
    #   ansible.builtin.debug:
    #     msg: "Retrying ({{ kind_cluster_install_retry }}/{{ kund_cluster_install_retries }})"

    - ansible.builtin.fail:
        msg: "kind failed"
    # - name: "Check that the kind executable exists"
    #   stat:
    #     path: "{{ kind_bin_path }}"
    #   register: rc_kind

    # - name: "Delete kind cluster"
    #   shell: "kind delete cluster --name {{ kind_cluster_name }}"
    #   when: rc_kind.stat.exists

    # - name: "Destroy current kind registry"
    #   shell: "docker rm -f kind-registry"
    #   failed_when: false

    # - name: "Installing Kind with registry"
    #   block:
    #     - name: "Generating file for kind and registry"
    #       template:
    #         src: kind-with-registry.sh.j2
    #         dest: "{{ kind_tmp_dir }}/kind-with-registry.sh"
    #         mode: "0755"

    #     - name: "Configuring Kind with registry"
    #       shell: "{{ kind_tmp_dir }}/kind-with-registry.sh"
    #   when: rc_kind.stat.exists

    # - name: "Make sure that '{{ testing_bin_path }}' exists"
    #   file:
    #     path: "{{ testing_bin_path }}"
    #     state: directory

    # - name: "Check if operator-sdk exists"
    #   stat:
    #     path: "{{ operator_sdk_bin_path }}"
    #   register: rkr_osdk

    # - name: "Install operator-sdk {{ operator_sdk_version }}"
    #   get_url:
    #     url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk-{{ operator_sdk_version }}-x86_64-linux-gnu
    #     dest: "{{ operator_sdk_bin_path }}"
    #     mode: "0755"
    #   register: operator_sdk_install_result
    #   until: operator_sdk_install_result.status_code is undefined or operator_sdk_install_result.status_code == 200
    #   retries: 10
    #   delay: 15
    #   failed_when: operator_sdk_install_result is failure
    #   when:
    #     - not rkr_osdk.stat.exists
    #     - not run_upstream|bool

    # - name: "Install operator-sdk {{ operator_sdk_version }}"
    #   get_url:
    #     url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk_linux_amd64
    #     dest: "{{ operator_sdk_bin_path }}"
    #     mode: "0755"
    #   register: operator_sdk_install_result
    #   until: operator_sdk_install_result.status_code is undefined or operator_sdk_install_result.status_code == 200
    #   retries: 10
    #   delay: 15
    #   failed_when: operator_sdk_install_result is failure
    #   when:
    #     - not rkr_osdk.stat.exists
    #     - run_upstream|bool

    # - name: "Installing OLM ({{ olm_version }})"
    #   shell: "{{ operator_sdk_bin_path }} olm install --version {{ olm_version }} --timeout 5m0s"
    #   register: olm_install_rc
  tags:
    - always
  rescue:
    - name: "Fail after {{ kund_cluster_install_retries }} retries"
      fail:
        msg: "Failed to install kind cluster '{{ kind_cluster_name }}' after ({{ kind_cluster_install_retry|int }}/{{ kund_cluster_install_retries }}) retries"
      when: kind_cluster_install_retry|int >= kund_cluster_install_retries|int

    - name: "Printing process info"
      debug:
        msg: "Failed to install kind - Going to retry ({{ kind_cluster_install_retry|int + 1 }}/{{ kund_cluster_install_retries }}) ..."

    - name: "Increase 'kind_cluster_install_retry' by 1"
      set_fact:
        kind_cluster_install_retry: "{{ kind_cluster_install_retry|int + 1 }}"

    - include_tasks: cluster_install.yml
