---
- name: "Delete kind cluster '{{ kind_cluster_name }}'"
  ansible.builtin.command: "{{ kind_binary }} delete cluster --name {{ kind_cluster_name }}"
  changed_when: true

- name: "Generating kind config file"
  ansible.builtin.template:
    src: kind_config.yaml.j2
    dest: "{{ kind_config_path }}"
    mode: "0644"

- name: "Create kind cluster '{{ kind_cluster_name }}'"
  ansible.builtin.command: "{{ kind_binary }} create cluster --name {{ kind_cluster_name }} --image kindest/node:{{ kind_kube_version }} --config={{ kind_config_path }}"
  changed_when: true
