---
- name: "Installing OLM ({{ olm_version }})"
  ansible.builtin.command: "{{ op_bin_dir }}/{{ operator_sdk_binary }} olm install --version {{ olm_version }} --timeout 5m0s"
  register: olm_install_rc
