- name: "Upstream community main playbook"
  hosts: all
  become: false
  gather_facts: true

  roles:
    - { role: include_vars, var_name: "uc_config", var_file: "upstream-community-config.yaml", var_remote_src: false }
    - { role: install_kind_cluster }

  tasks:
    - name: "Print 'config'"
      debug:
        var: uc_config
